#!/bin/bash

function createOrg() {
  # ex) userlog-org1
  ORG=$1
  CA_PORT=$2
  CA_ORG=$3
  PEER_CNT=$4

  while :
  do
    if [ ! -f "organizations/fabric-ca/${CA_ORG}/tls-cert.pem" ]; then
      sleep 1
    else
      break
    fi
  done

  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/${ORG}.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/${ORG}.example.com/

  set -x
  ./bin/fabric-ca-client enroll -u https://admin:adminpw@localhost:${CA_PORT} --caname ca-${CA_ORG} --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-${CA_PORT}-ca-${CA_ORG}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-${CA_PORT}-ca-${CA_ORG}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-${CA_PORT}-ca-${CA_ORG}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-${CA_PORT}-ca-${CA_ORG}.pem
    OrganizationalUnitIdentifier: orderer" > "${PWD}/organizations/peerOrganizations/${ORG}.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORG}.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORG}.example.com/msp/tlscacerts/ca.crt"

  # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORG}.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORG}.example.com/tlsca/tlsca.${ORG}.example.com-cert.pem"

  # Copy org1's CA cert to org1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORG}.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORG}.example.com/ca/ca.${ORG}.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  ./bin/fabric-ca-client register --caname ca-${CA_ORG} --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  ./bin/fabric-ca-client register --caname ca-${CA_ORG} --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  ./bin/fabric-ca-client register --caname ca-${CA_ORG} --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  for i in $(seq 0 $((PEER_CNT-1)))
  do
    infoln "Generating the peer${i} msp"
    set -x
    ./bin/fabric-ca-client enroll -u https://peer0:peer0pw@localhost:${CA_PORT} --caname ca-${CA_ORG} -M "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/msp" --csr.hosts "peer${i}.${ORG}.example.com" --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/${ORG}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/msp/config.yaml"

    infoln "Generating the peer0-tls certificates"
    set -x
    ./bin/fabric-ca-client enroll -u https://peer0:peer0pw@localhost:${CA_PORT} --caname ca-${CA_ORG} -M "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls" --enrollment.profile tls --csr.hosts "peer${i}.${ORG}.example.com" --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/${ORG}.example.com/peers/peer${i}.${ORG}.example.com/tls/server.key"
  done

  infoln "Generating the user msp"
  set -x
  ./bin/fabric-ca-client enroll -u https://user1:user1pw@localhost:${CA_PORT} --caname ca-${CA_ORG} -M "${PWD}/organizations/peerOrganizations/${ORG}.example.com/users/User1@${ORG}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORG}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORG}.example.com/users/User1@${ORG}.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  ./bin/fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:${CA_PORT} --caname ca-${CA_ORG} -M "${PWD}/organizations/peerOrganizations/${ORG}.example.com/users/Admin@${ORG}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${CA_ORG}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORG}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORG}.example.com/users/Admin@${ORG}.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  ./bin/fabric-ca-client enroll -u https://admin:adminpw@localhost:4054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-4054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-4054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-4054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-4054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  ./bin/fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  ./bin/fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  ./bin/fabric-ca-client enroll -u https://orderer:ordererpw@localhost:4054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/msp" --csr.hosts orderer-userlog.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  ./bin/fabric-ca-client enroll -u https://orderer:ordererpw@localhost:4054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls" --enrollment.profile tls --csr.hosts orderer-userlog.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer-userlog.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  ./bin/fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:4054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
